environment:
  PYTHON: "C:\\Python27-x64"
  CMAKE_URL: "https://cmake.org/files/v3.14/cmake-3.14.0-rc1-win64-x64.zip"
  MSVC_HOME: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"

os:
  - Visual Studio 2017

build:
  verbosity: detailed

install:
  # Python
  - set PATH=%PYTHON%;%PATH%

  # Get CMake
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\cmake > nul
  - set PATH=C:\cmake\bin;%PATH%
  - cmake --version

  # Clang-cl
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v

before_build:
  - call "%MSVC_HOME%\VC\Auxiliary\Build\vcvarsall.bat" x86
  - python -m pip install xlsxwriter pycryptodome pypiwin32
  - cd C:\projects\cb-multios

build_script:
  - ps: .\build.ps1
